### PR TITLE
(for review) remove colorful-logging and wasm code

### PR DESCRIPTION
**Pull request by Oreolek**
- no colorful-logging dependency
- no wasm
- minor package updates
- inklecate update
- ink test updates
- local jest instead of global jest (but still no jest tests …?)

### CODE REVIEW

**Comment by furkle** [comment]
wow, this is extremely thorough, thanks so much! tests are definitely something i need to add -- a lot of this work got interrupted by a lot of chaos in my life, and other things demanding my attention more loudly. i'll look at this PR later and a reasonable, small test set will be the next order of business.

thanks again!

**Comment by furkle** [comment]
and now i, always seeing the "thank you" as the first order of business, realize you already added a thorough base test case. thank you for that too!

**Comment by Oreolek** [comment]
I didn't add anything, it's all your old tests. I just fixed the ink code for recent inklecate.

**Comment by furkle** [comment]
hah, well, you can see how well i remember it, then. i'll look it over in a bit and accept or modify it, i won't make you fix any issues i run into yourself.

**Pull request merged**
